/**
 * # A2A V3 Provider for AI SDK
 *
 * This package provides a `LanguageModelV3` implementation that bridges the
 * [Vercel AI SDK](https://sdk.vercel.ai/) with the [A2A (Agent-to-Agent) Protocol](https://a2a-protocol.org/).
 *
 * ## What is A2A?
 *
 * A2A is a protocol for inter-agent communication that defines how AI agents
 * discover each other, exchange messages, and collaborate on tasks. Key concepts:
 *
 * - **Agent Card**: JSON metadata describing an agent's capabilities, endpoint, and auth
 * - **Task**: A stateful unit of work with lifecycle (submitted → working → completed/input-required)
 * - **Message**: A single turn of communication containing Parts
 * - **Part**: Content container (TextPart, FilePart, DataPart)
 * - **Artifact**: Tangible output generated by an agent
 *
 * ## What is AI SDK?
 *
 * The Vercel AI SDK provides a unified interface for working with language models.
 * This provider implements `LanguageModelV3` so you can use A2A agents with
 * `generateText()`, `streamText()`, and other AI SDK functions.
 *
 * ## Integration Overview
 *
 * ```
 * ┌─────────────┐    ┌──────────────────┐    ┌─────────────┐
 * │   AI SDK    │───▶│ a2a-ai-provider  │───▶│  A2A Agent  │
 * │ generateText│    │ (this package)   │    │  (server)   │
 * └─────────────┘    └──────────────────┘    └─────────────┘
 *       │                    │                     │
 *   LanguageModelV3      Converts to/from      A2A Protocol
 *   prompt/response      A2A Messages          JSON-RPC/SSE
 * ```
 *
 * ## Quick Start
 *
 * ```typescript
 * import { a2aV3 } from '@drew-foxall/a2a-ai-provider-v3';
 * import { generateText } from 'ai';
 *
 * const result = await generateText({
 *   model: a2aV3('http://localhost:3001'),
 *   prompt: 'Plan a trip to Paris',
 * });
 *
 * // Access A2A-specific metadata
 * const { taskId, contextId, inputRequired } = result.providerMetadata?.a2a ?? {};
 * ```
 *
 * @see https://a2a-protocol.org/ - A2A Protocol documentation
 * @see https://sdk.vercel.ai/ - AI SDK documentation
 *
 * @packageDocumentation
 */

// =============================================================================
// Agent Discovery
// Helpers for finding A2A agents via well-known URIs or direct URLs
// @see https://a2a-protocol.org/latest/topics/agent-discovery/
// =============================================================================
export type { DiscoveryOptions, DiscoveryResult } from "./discovery.js";
export {
  AgentDiscoveryError,
  discoverAgent,
  fetchAgentCard,
  getAuthSchemes,
  supportsCapability,
} from "./discovery.js";

// =============================================================================
// Language Model
// The core LanguageModelV3 implementation that wraps A2A protocol communication
// =============================================================================
export { A2aV3LanguageModel } from "./model.js";

// =============================================================================
// Provider Factory
// Functions to create A2A language model instances for use with AI SDK
// =============================================================================
export type { A2aV3ChatSettings, A2aV3Provider, A2aV3ProviderSettings } from "./provider.js";
export { a2aV3, createA2aV3 } from "./provider.js";

// =============================================================================
// Types
// Type definitions for A2A protocol structures exposed via providerMetadata
// =============================================================================
export type {
  /** Union of all A2A streaming event types */
  A2AStreamEventData,
  /** A2A metadata exposed in result.providerMetadata.a2a */
  A2aProviderMetadata,
  /** Options passed via providerOptions.a2a in generateText/streamText */
  A2aProviderOptions,
  /** Serialized artifact for JSON transport */
  A2aSerializedArtifact,
  /** Serialized file info for JSON transport */
  A2aSerializedFile,
  /** Serialized message part (text/file/data) for JSON transport */
  A2aSerializedPart,
  /** Serialized status message for JSON transport */
  A2aSerializedStatusMessage,
  /** Internal model configuration */
  A2aV3ModelConfig,
} from "./types.js";

// =============================================================================
// Type Guards & Conversion Utilities
// Helpers for type-safe handling of A2A ↔ AI SDK data conversion
// =============================================================================
export {
  /** Create empty A2aProviderMetadata for initialization */
  createEmptyMetadata,
  /** Convert AI SDK JSONObject back to A2A Record<string, unknown> */
  fromJSONObject,
  /** Extract typed A2aProviderOptions from providerOptions */
  getA2aOptions,
  /** Type guard: is value A2aProviderOptions? */
  isA2aProviderOptions,
  /** Type guard: is value a valid JSONValue? */
  isJSONValue,
  /** Type guard: is value Record<string, unknown>? */
  isRecordStringUnknown,
  /** Type guard: is value A2aSerializedPart? */
  isSerializedPart,
  /** Type guard: is value A2aSerializedPart[]? */
  isSerializedPartArray,
  /** Type guard: is value string? */
  isString,
  /** Type guard: is value Uint8Array? */
  isUint8Array,
  /** Convert A2A Record<string, unknown> to AI SDK JSONObject */
  toJSONObject,
  /** Convert nullable A2A metadata to JSONObject | null */
  toJSONObjectOrNull,
  /** Wrap A2aProviderMetadata in SharedV3ProviderMetadata structure */
  wrapProviderMetadata,
} from "./types.js";

// =============================================================================
// Advanced Utilities
// Low-level helpers for custom A2A integrations
// =============================================================================
export {
  /** Convert A2aSerializedPart back to A2A SDK Part */
  deserializePart,
  /** Extract A2aProviderMetadata from A2A Task or Message response */
  extractA2aMetadata,
  /** Extract response metadata (id, timestamp) from A2A events */
  getResponseMetadata,
  /** Type guard: is A2A Part a DataPart? */
  isDataPart,
  /** Type guard: is A2A Part a FilePart? */
  isFilePart,
  /** Type guard: is FilePart using bytes (base64)? */
  isFilePartWithBytes,
  /** Type guard: is FilePart using URI? */
  isFilePartWithUri,
  /** Type guard: is A2A Part a TextPart? */
  isTextPart,
  /** Map A2A TaskStatusUpdateEvent to LanguageModelV3FinishReason */
  mapFinishReason,
  /** Map A2A TaskState to LanguageModelV3FinishReason */
  mapTaskStateToFinishReason,
  /** Convert A2A SDK Part to A2aSerializedPart for JSON transport */
  serializePart,
} from "./utils.js";
